config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books do
    resources :reviews
  end
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  post 'login', to: "sessions#create"

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  # get 'sessions/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :transactions, dependent: :destroy
  validates :email, presence: true, uniqueness: true,
            format: { with: /\A(\S+)@(.+)\.(\S+)\z/, message: "must be a valid email address" }
  has_many :reviews, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :phone_number, length: {is: 10}, allow_blank: true
  validates :credit_card_number, length: {is: 16}, allow_blank: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]
  # GET /users or /users.json
  def index
    if !current_user.admin?
      redirect_to root_path
    else
      @users = User.all
    end
  end

  # GET /users/1 or /users/1.json
  def show
    if !current_user.admin?
      @user = current_user
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    session[:id] = nil
    @user.destroy

    respond_to do |format|
      if @user.admin?
        format.html { redirect_to user_url, notice: "User was successfully destroyed." }
      else
        format.html { redirect_to users_path, notice: "User was successfully destroyed." }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :name, :email, :address, :credit_card_number, :phone_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>* indicates required field</strong>
  </p>

  <div class="field">
    <%= form.label :name, 'name*' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, 'email*' %>
    <%= form.text_field :email %>
  </div>

  <% if !@user.admin? %>
    <div class="field">
      <%= form.label :username, 'username*' %>
      <%= form.text_field :username %>
    </div>

    <div class="field">
      <%= form.label :password, 'password*' %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation, 'password confirmation*' %>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_area :address %>
    </div>

    <div class="field">
      <%= form.label :credit_card_number %>
      <%= form.text_area :credit_card_number %>
    </div>

    <div class="field">
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Credit card number:</strong>
    <%= user.credit_card_number %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= user.phone_number %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% if !current_user.admin? %>
  <%= render "form", user: current_user %>
<% else %>
  <%= render "form", user: @user %>
<% end %>


  <br>

<div>
  <%= link_to "Back to user", @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>Email address</th>
    <th>Address</th>
    <th>Phone number</th>
    <th>Credit card number</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if !user.admin? %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.address %></td>
          <td><%= user.phone_number %></td>
          <td><%= user.credit_card_number %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= button_to 'Delete', user, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email %>
</p>

<% if !@user.admin? %>
  <p>
    <strong>Address:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @user.phone_number %>
  </p>

  <p>
    <strong>Credit card number:</strong>
    <%= @user.credit_card_number %>
  </p>
<% end %>

<% if current_user.reviews.any?%>
  <div class="row">
    <div class="col-sm-6">
      <h4>Reviews Given</h4>
      <ul>
        <table>
    <thead>
        <tr>
            <th>Book</th>
            <th>Review</th>
            <th>Rating (/5)</th>
        </tr>
    </thead>
    <tbody>
        <% @user.reviews.each do |review|%>
            <tr>
                <td style="text-align:center"> <%= review.book.name%></td>&nbsp;&nbsp;&nbsp;&nbsp;
                <td style="text-align:center"> <%= review.review%></td>&nbsp;&nbsp;&nbsp;&nbsp;
                <td style="text-align:center"> <%= review.rating%></td> 
                <td> <%= link_to "Show this review", book_review_path(review.book, review) %>
            </tr>
        <%end%>
    </tbody>
</table>
        <% else %>
        <p>No Reviews yet!</p>
        <% end %>
      </ul>
    </div>
  </div>

<%= link_to 'Edit', edit_user_path(@user) %>  |
<%= link_to 'Back', root_path %><br><br>
<% if !current_user.admin? %>
  <%= button_to "Delete", @user, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<% end %>