config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books do
    resources :reviews
  end
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  post 'login', to: "sessions#create"

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  # get 'sessions/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Book Shopping Portal</h1>
<p>Purchase books at the snap of your finger</p>
<% if current_user %>
  Logged in as <%= current_user.name %>.<br><br>
  <%= link_to 'View Profile', current_user %><br>
  <%= link_to 'View purchase history', transactions_path%><br>
  <%= link_to 'View all books', books_path %><br>
  <% if current_user.admin?%>
    <%= link_to 'View All Profiles', users_path %><br>
  <% end %>
  <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to "Signup", signup_path %> or
  <%= link_to "Login", login_path %>
<% end %>