config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books do
    resources :reviews
  end
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  post 'login', to: "sessions#create"

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  # get 'sessions/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :transactions, dependent: :destroy
    validates :name, presence: true
    validates :author, presence: true
    validates :publisher, presence: true
    validates :price, presence: true, numericality: {greater_than: 0}
    validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 0,
                                                     only_integer: true}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    if params[:search_by_author].present?
      @books = Book.where('lower(author) =?',params[:search_by_author].downcase)
    elsif params[:search_by_book].present?
      @books = Book.where('lower(name) =?',params[:search_by_book].downcase)
    elsif params[:search_by_rating].present?
      @books = Book.where(id: Review.where('rating > ?', params[:search_by_rating]).pluck(:book_id))
    else
      @books = Book.all
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    if !current_user.admin?
      flash[:notice] = "Not able to access this"
      redirect_to root_path
      return
    else
      @book = Book.new
    end
  end

  # GET /books/1/edit
  def edit
    if !current_user.admin?
      flash[:notice] = "Not able to access this"
      redirect_to root_path
      return
    end
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id]) unless action_name == "index"
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:name, :author, :publisher, :price, :quantity)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Name:</strong>
    <%= book.name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.publisher %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= book.quantity %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :publisher, style: "display: block" %>
    <%= form.text_field :publisher %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<% if current_user.admin? %>
<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>
  <%else %>
  <%= "Not authorized to edit book details" %>
<%end %>

app/views/books/index.html.erb
<td><%= link_to 'View Cart', cart_path %></td>
<%= form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search_by_author, params[:search_by_author], placeholder: "Enter Author" %>
    <%= submit_tag "search", :author => nil%>
  </p>
<% end %>
<%= form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search_by_book, params[:search_by_book], placeholder: "Enter Book" %>
    <%= submit_tag "search", :name => nil %>
  </p>
<% end %>
<%= form_tag books_path, :method => 'get' do %>
  <p> Enter the rating:
    <%= number_field_tag :search_by_rating, params[:search_by_rating], min: 0, max: 5, step: 0.1, placeholder: "Enter Book" %>
    <%= submit_tag "search", :name => nil %>
  </p>
<% end %>

<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<% if current_user.admin? %>
  <%= link_to "Add New book", new_book_path %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Publisher</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Rating(/5)</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.publisher %></td>
      <td><%= book.price %></td>
      <td><%= book.quantity %></td>
      <% if book.reviews.any? %>
      <td><%= book.reviews.average(:rating).round(2)%></td>
        <% else %>
        <td><%= 'No Rating'%></td>
      <% end %>
      <td><a href="/cart/<%= book.id %>">Add to Cart</a></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Reviews', book_reviews_path(book) %></td>
      <td><%= link_to_if book.quantity > 0, 'Purchase', new_transaction_path(:book_id => book.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table><br><br>
  <td><%= link_to "Back", root_path %></td>

app/views/books/new.html.erb
<h1>New book</h1>
<% if current_user.admin? %>
<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>
<%else %>
  <%= "Not authorized to add a new book" %>
<%end %>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <% if current_user.admin? %>
    <%= link_to "Edit this book", edit_book_path(@book) %>
    <%= button_to "Delete this book", @book, method: :delete %>
  <%end %>
  <%= link_to "Reviews", book_reviews_path(@book)%> |
  <%= link_to "Back to books", books_path %>


</div>