config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books do
    resources :reviews
  end
  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  post 'login', to: "sessions#create"

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  # get 'sessions/index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    #debugger
    if params[:search_by_username].present?
      @reviews = Review.where(user: User.where(username: params[:search_by_username]).first,book: @book)
  end
end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    if current_user.id!=@review.user_id and current_user.username!="AdminUser"
      flash[:notice] = "Not able to access this"
      redirect_to root_path
    end
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.book=@book
    @review.user=@current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to book_reviews_path, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to book_reviews_path, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to book_reviews_path, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book=Book.find(params[:book_id])
    end

    def set_review
      #@review = Review.find(params[:id])
      @review = @book.reviews.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :review)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: [@book,review]) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating, min: 1, max: 5 %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= review.review %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%
=begin%>
 <%= link_to "Show this review", @review %> | 
<%
=end%>
  <%= link_to "Back to reviews", book_review_path(@book) %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<%= form_tag book_reviews_path(@book), :method => 'get' do %>
  <p>
    <%= text_field_tag :search_by_username,nil, placeholder: "Enter username" %>
    <%= submit_tag "search", :name => nil %>
  </p>
<% end %>

<% if @reviews == nil %>
<div id="reviews">
  <% if !@book.reviews.any?%>
      <p>No reviews for this book yet!</p>
  <%else%>
  <% @book.reviews.each do |review| %>
    <%= render review %>
    <p><strong>Name of the book:  </strong><%= @book.name%></p>
    <p><strong>Review by user:  </strong><%= User.find(review.user_id).username%></p>
  <p><%= link_to "Show this review", book_review_path(review.book, review) %></p>
  <% end %>
  <%end%>
<%else%>
<% @reviews.each do |review| %>
    <%= render review %>
    <p><strong>Name of the book:  </strong><%= @book.name%></p>
    <p><strong>Review by user:  </strong><%= User.find(review.user_id).username%></p>
  <p><%= link_to "Show this review", book_review_path(review.book, review) %></p>
<% end %>
<% end %>

</div>

<%= link_to "Write a new review", new_book_review_path(@book) %><br><br>
<%= link_to "Back", books_path%>

app/views/reviews/new.html.erb
<h1>New review</h1>
<p><strong>Review for the book:  </strong><%= @book.name%></p>
<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", book_reviews_path(@book) %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= form_tag book_reviews_path(@book), :method => 'get' do %>
  <p>
    <%= text_field_tag :search_by_username, params[:search_by_username], placeholder: "Enter username" %>
    <%= submit_tag "search", :name => nil %>
  </p>
<% end %>

<%= render @review %>
<p><strong>Name of the book:  </strong><%= @book.name%></p>
<p><strong>Review by user:  </strong><%= User.find(@review.user_id).username%></p>

<div>
  <%= link_to "Edit this review", edit_book_review_path(@book,@review) if current_user.id === @review.user_id or current_user.admin %> <br><br>
  <%= link_to "Back to reviews", book_reviews_path(@book) %> <br><br>
  <%= button_to "Delete this review", book_review_path(@book, @review), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if current_user.id === @review.user_id or current_user.admin%> <br>
</div> 